### PR TITLE
Note Python 3.5 Compatibility

### PR DESCRIPTION
**Pull request by jnmclarty**
I noticed the travis instructions were updated in 2015.  I haven't fully battle tested this myself on 3.5, but I'm curious if the maintainers are ready to advertise the compatibility.  If so, merge away!

### CODE REVIEW

**Comment by jnmclarty** [comment]
Looks like there's multiple problems with python 3.x test suite.  Is it just the test suite, or is it actually not compatible with 3.3? And 3.5?  Are the maintainers interested in help to fix this?

**Comment by maciejlach** [comment]
It looks like numpy 1.12 drops support for Python 3.3 which is listed present in qPython Travis config, thus the build is now failing on Travis. There is number of possible solutions here:

- drop the support for Python 3.3, add support for 3.5 and adjust required version of numpy,
- set the numpy requirement to prevent upgrading to 1.12.

In addition there is an issue with one of unit tests on Python 3.x. I will prepare a fix for this.

Also, the project would benefit from switching to tox for testing multiple Python versions. I plan to prepare a pull request addressing this topic. Unfortunately, I'm now longer actively working on the project, and cannot promise any time boundaries.

**Comment by SKolodynski** [comment]
I am in favor of dropping support for Python 3.3 and adding support for 3.5

**Comment by mrecht** [comment]
I am in favor of dropping support for Python 3.3 and adding support for 3.5



+1

**Comment by maciejlach** [comment]
I pushed a pull request with unit test fix. This also adds support for 3.6 and drops 3.3.

Due to changes in supported Python versions, I would suggest to bump the qpython version to 1.3. This is reflected already in Changelog, but you have to bump the version in `__init__.py`.

**Pull request merged**
